### ISSUE TITLE
Launchd.launch_events does not work when feature `plist` is not enabled.

### ISSUE THREAD

**Issue by koenichiwa** [koenichiwa/launchd#3]
From the source:
``` rust
#[cfg(feature = "plist")]
use plist::Value;

pub struct Launchd {
// ..
    launch_events: Option<LaunchEvents>,
// ... 
}

#[cfg(feature = "plist")]
type LaunchEvents = HashMap<String, HashMap<String, HashMap<String, Value>>>;

// TODO: the current implementation is dependent on plist. Is this necessary?
#[cfg(not(feature = "plist"))]
type LaunchEvents = ();
```

One option could be to make the plist feature non-optional. Another might be to implement another type instead of plist::Value. Still looking for other options

**Comment by dsully** [comment]
My opinion is the `plist` feature should be the default. Is the concern about adding "bloat" to a build?

**Comment by koenichiwa** [comment]
>Is the concern about adding "bloat" to a build?

Yes IIRC that was my original concern. I wanted to give anyone who needed the library to have complete control over what they needed or not. I might've went overboard with that. What would you advise?

**Comment by dsully** [comment]
I wouldn't worry about it. So many projects already include serde.

**Comment by koenichiwa** [comment]
Alright, you know what, I'll just simplify it and remove it as a feature.
If someone needs it to be split, then they can open a  new issue.
